baseURL = "https://0x148.com/"
copyright = "Copyright (c) Yang Sheng Han."
defaultContentLanguage = "en-us"
disableAliases = true
enableRobotsTXT = true
hasCJKLanguage = true
PygmentsOptions = "linenos=table"
pygmentsUseClasses = true
relativeURLs = true
summaryLength = 140
