themeColor = "#114488"
backgroundColor = "#F4F4F4"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"

comments = true
math = true
share = true
toc = true

ampIFrameBase = "https://iframe.0x148.com/"
ampComponents = ["amp-sidebar", "amp-analytics", "amp-form", "amp-iframe", "amp-consent"]
ampModules = ["google-analytics"]
htmlModules = ["google-analytics", "disqus", "katex", "katex-auto-render", "katex-copy-tex", "holderjs"]

navbarMenuName = "navbar"
navbarLinkName = "link"

pgpFingerPrint = "11BEC92C73656BE7C4D1EC61546B738781027B88"
